services:
  app:
    build:
      context: .
      dockerfile: /workspaces/BancodeDados/.devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: pratica
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: pratica_db
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pratica -d pratica_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: